"""Shared mapping tables for country and indicator codes."""

from __future__ import annotations

from typing import Final


def normalize_key(value: str) -> str:
    """Normalize a mapping key for lookup."""
    return value.lower().strip()


# ISO 3166-1 Alpha-2 codes (2-letter, e.g., "US", "GB")
# Used by: World Bank API, socioeconomic.py
COUNTRY_CODES_ISO2: Final[dict[str, str]] = {
    "usa": "US",
    "united states": "US",
    "america": "US",
    "uk": "GB",
    "united kingdom": "GB",
    "britain": "GB",
    "england": "GB",
    "china": "CN",
    "japan": "JP",
    "germany": "DE",
    "france": "FR",
    "india": "IN",
    "brazil": "BR",
    "russia": "RU",
    "canada": "CA",
    "australia": "AU",
    "italy": "IT",
    "spain": "ES",
    "mexico": "MX",
    "south korea": "KR",
    "korea": "KR",
    "indonesia": "ID",
    "netherlands": "NL",
    "switzerland": "CH",
    "sweden": "SE",
    "poland": "PL",
    "belgium": "BE",
    "argentina": "AR",
    "nigeria": "NG",
    "south africa": "ZA",
    "egypt": "EG",
    "pakistan": "PK",
    "bangladesh": "BD",
    "vietnam": "VN",
    "philippines": "PH",
    "thailand": "TH",
    "malaysia": "MY",
    "singapore": "SG",
    "new zealand": "NZ",
    "ireland": "IE",
    "portugal": "PT",
    "greece": "GR",
    "czech republic": "CZ",
    "romania": "RO",
    "hungary": "HU",
    "austria": "AT",
    "israel": "IL",
    "saudi arabia": "SA",
    "uae": "AE",
    "united arab emirates": "AE",
    "turkey": "TR",
    "norway": "NO",
    "denmark": "DK",
    "finland": "FI",
    "chile": "CL",
    "colombia": "CO",
    "peru": "PE",
    "venezuela": "VE",
    "ukraine": "UA",
    "chad": "TD",
    "ethiopia": "ET",
    "ghana": "GH",
    "kenya": "KE",
    "tanzania": "TZ",
    "uganda": "UG",
}

# ISO 3166-1 Alpha-3 codes (3-letter, e.g., "USA", "GBR")
# Used by: ILO API (labor.py), World Bank API (gender.py)
COUNTRY_CODES_ISO3: Final[dict[str, str]] = {
    "brazil": "BRA",
    "chad": "TCD",
    "china": "CHN",
    "ethiopia": "ETH",
    "france": "FRA",
    "germany": "DEU",
    "ghana": "GHA",
    "india": "IND",
    "indonesia": "IDN",
    "japan": "JPN",
    "kenya": "KEN",
    "mexico": "MEX",
    "nigeria": "NGA",
    "south africa": "ZAF",
    "spain": "ESP",
    "tanzania": "TZA",
    "uganda": "UGA",
    "united kingdom": "GBR",
    "uk": "GBR",
    "usa": "USA",
    "united states": "USA",
    "vietnam": "VNM",
    "world": "WLD",
    # Additional common countries
    "argentina": "ARG",
    "australia": "AUS",
    "austria": "AUT",
    "bangladesh": "BGD",
    "belgium": "BEL",
    "canada": "CAN",
    "chile": "CHL",
    "colombia": "COL",
    "denmark": "DNK",
    "egypt": "EGY",
    "finland": "FIN",
    "greece": "GRC",
    "hungary": "HUN",
    "ireland": "IRL",
    "israel": "ISR",
    "italy": "ITA",
    "malaysia": "MYS",
    "netherlands": "NLD",
    "new zealand": "NZL",
    "norway": "NOR",
    "pakistan": "PAK",
    "peru": "PER",
    "philippines": "PHL",
    "poland": "POL",
    "portugal": "PRT",
    "romania": "ROU",
    "russia": "RUS",
    "saudi arabia": "SAU",
    "singapore": "SGP",
    "south korea": "KOR",
    "korea": "KOR",
    "sweden": "SWE",
    "switzerland": "CHE",
    "thailand": "THA",
    "turkey": "TUR",
    "uae": "ARE",
    "united arab emirates": "ARE",
    "ukraine": "UKR",
    "venezuela": "VEN",
}

COUNTRY_CODES_SDG: Final[dict[str, int]] = {
    "world": 1,
    "global": 1,
    "afghanistan": 4,
    "albania": 8,
    "algeria": 12,
    "argentina": 32,
    "australia": 36,
    "austria": 40,
    "bangladesh": 50,
    "belgium": 56,
    "brazil": 76,
    "canada": 124,
    "chile": 152,
    "china": 156,
    "colombia": 170,
    "democratic republic of the congo": 180,
    "drc": 180,
    "congo": 178,
    "denmark": 208,
    "egypt": 818,
    "ethiopia": 231,
    "finland": 246,
    "france": 250,
    "germany": 276,
    "ghana": 288,
    "greece": 300,
    "india": 356,
    "indonesia": 360,
    "iran": 364,
    "iraq": 368,
    "ireland": 372,
    "israel": 376,
    "italy": 380,
    "japan": 392,
    "jordan": 400,
    "kenya": 404,
    "south korea": 410,
    "korea": 410,
    "malaysia": 458,
    "mexico": 484,
    "morocco": 504,
    "mozambique": 508,
    "myanmar": 104,
    "nepal": 524,
    "netherlands": 528,
    "new zealand": 554,
    "nigeria": 566,
    "norway": 578,
    "pakistan": 586,
    "peru": 604,
    "philippines": 608,
    "poland": 616,
    "portugal": 620,
    "russia": 643,
    "russian federation": 643,
    "saudi arabia": 682,
    "senegal": 686,
    "singapore": 702,
    "south africa": 710,
    "spain": 724,
    "sri lanka": 144,
    "sweden": 752,
    "switzerland": 756,
    "tanzania": 834,
    "thailand": 764,
    "turkey": 792,
    "uganda": 800,
    "ukraine": 804,
    "united arab emirates": 784,
    "uae": 784,
    "united kingdom": 826,
    "uk": 826,
    "united states": 840,
    "usa": 840,
    "us": 840,
    "vietnam": 704,
    "zambia": 894,
    "zimbabwe": 716,
    "africa": 2,
    "sub-saharan africa": 202,
    "northern africa": 15,
    "eastern africa": 14,
    "western africa": 11,
    "asia": 142,
    "europe": 150,
    "latin america": 419,
    "oceania": 9,
}

COUNTRY_CODES_FAO: Final[dict[str, int]] = {
    "brazil": 21,
    "chad": 39,
    "china": 41,
    "ethiopia": 62,
    "france": 68,
    "germany": 79,
    "ghana": 81,
    "india": 100,
    "indonesia": 101,
    "japan": 110,
    "kenya": 114,
    "mexico": 138,
    "nigeria": 159,
    "south africa": 202,
    "spain": 203,
    "tanzania": 215,
    "uganda": 226,
    "united kingdom": 229,
    "uk": 229,
    "usa": 231,
    "united states": 231,
    "vietnam": 237,
}


def get_iso3_code(country: str) -> str:
    """Convert country name to ISO 3166-1 Alpha-3 code.

    Args:
        country: Country name or existing code

    Returns:
        ISO 3-letter country code (uppercase)
    """
    normalized = normalize_key(country)

    # Check mapping first
    if normalized in COUNTRY_CODES_ISO3:
        return COUNTRY_CODES_ISO3[normalized]

    # If already a 3-letter code, return uppercase
    if len(country) == 3 and country.isalpha():
        return country.upper()

    # Fallback: truncate to 3 chars (may not be valid but API might accept)
    return country.upper()[:3]
